### ISSUE TITLE
Make content searchable

### ISSUE THREAD

**Issue by vjanssens** [KPN-CISO/kpn-security-policy#2]
Currently, the contents of the PDF's can't be indexed by Github and thus searching through them is impossible. Would it be possible to automatically generate Markdown files (or something similar)?

**Comment by okoeroo** [comment]
I will take that issue and forward this to our developers. This will take some time.

**Comment by Yomodo** [comment]
2021, need more time?

**Comment by okoeroo** [comment]
To clarify: we took a different route. We publish on https://ciso-ksp.kpnnet.org and a copy elsewhere is currently not scheduled. That site is being updated per KSP release cycle in sync with the internal source data 1 to 1, minus de guideline documents nor tools, which are tied to internal processes and contacts.
